spring:
  datasource:
    url: jdbc:mysql://39.106.107.127/sproject?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8070
mybatis:
  mapper-locations: classpath:mapper/*.xml
